export const DEMO_MODE = import.meta.env.VITE_DEMO_MODE === "true";

export const demoStats = {
  total_requests: 29,
  successful_requests: 27,
  failed_requests: 2,
  fallback_count: 6,
  avg_latency: 4.4963,
  total_estimated_cost_usd: 0,
  free_model_usage_count: 24,
  requests_using_free_models: 24,
  cost_saved_estimate: 1.283,
  requests_by_actual_model: {
    "openai/gpt-oss-120b:free": 8,
    "google/gemma-3n-e2b-it:free": 5,
    "google/gemma-3n-e4b-it:free": 4,
    "gpt-4o": 3,
  },
  requests_by_provider: {
    openrouter: 24,
    openai: 5,
  },
  usage_by_provider: {
    openrouter: 24,
    openai: 5,
  },
  performance_by_model: {
    "openai/gpt-oss-120b:free": {
      success_rate: 1,
      avg_latency: 2.2201,
      avg_cost: 0,
      latency_score: 0.403,
      cost_score: 1,
      confidence: 1,
      score: 0.821,
      sample_count: 6,
    },
    "google/gemma-3n-e2b-it:free": {
      success_rate: 1,
      avg_latency: 3.4303,
      avg_cost: 0,
      latency_score: 0.304,
      cost_score: 1,
      confidence: 1,
      score: 0.791,
      sample_count: 3,
    },
  },
  candidate_scores: [
    {
      rank: 1,
      model_id: "openai/gpt-oss-120b:free",
      provider: "openrouter",
      is_free: true,
      enabled: true,
      success_rate: 1,
      avg_latency: 2.2201,
      avg_cost: 0,
      latency_score: 0.403,
      cost_score: 1,
      confidence: 1,
      score: 0.821,
      sample_count: 6,
      excluded: false,
      exclusion_reason: null,
    },
    {
      rank: 2,
      model_id: "google/gemma-3n-e2b-it:free",
      provider: "openrouter",
      is_free: true,
      enabled: true,
      success_rate: 1,
      avg_latency: 3.4303,
      avg_cost: 0,
      latency_score: 0.304,
      cost_score: 1,
      confidence: 1,
      score: 0.791,
      sample_count: 3,
      excluded: false,
      exclusion_reason: null,
    },
    {
      rank: 3,
      model_id: "openrouter/free",
      provider: "openrouter",
      is_free: true,
      enabled: true,
      success_rate: 1,
      avg_latency: 6.5032,
      avg_cost: 0,
      latency_score: 0.187,
      cost_score: 1,
      confidence: 1,
      score: 0.756,
      sample_count: 16,
      excluded: false,
      exclusion_reason: null,
    },
  ],
};

export const demoLogs = [
  {
    id: 201,
    timestamp: "2026-03-22T13:58:00Z",
    original_model: "clawhelm-auto",
    selected_model: "openrouter/free",
    actual_model: "openai/gpt-oss-120b:free",
    model_display_name: "openrouter/free -> openai/gpt-oss-120b:free",
    provider: "openrouter",
    is_free_model: true,
    model_source: "available_pool",
    routing_reason: "selected based on performance score",
    routing_score: 0.821,
    status_code: 200,
    fallback_used: false,
    prompt: "[{\"role\":\"user\",\"content\":\"Plan a suspiciously over-engineered birthday party for a cat named Kernel.\"}]",
    response: "Kernel deserves a launch sequence, not a party.",
    latency: 2.2201,
    total_tokens: 124,
    estimated_cost: 0,
  },
  {
    id: 200,
    timestamp: "2026-03-22T13:54:31Z",
    original_model: "clawhelm-auto",
    selected_model: "google/gemma-3n-e2b-it:free",
    actual_model: "google/gemma-3n-e2b-it:free",
    model_display_name: "google/gemma-3n-e2b-it:free",
    provider: "openrouter",
    is_free_model: true,
    model_source: "available_pool",
    routing_reason: "fallback escalation",
    routing_score: 0.791,
    status_code: 200,
    fallback_used: true,
    prompt: "[{\"role\":\"user\",\"content\":\"Give me a tagline for the invitation.\"}]",
    response: "\"ClawHelm presents: Kernel One.\"",
    latency: 3.6757,
    total_tokens: 117,
    estimated_cost: 0,
  },
];

export function buildDemoChatResponse(messages) {
  const latestUser = [...messages].reverse().find((message) => message.role === "user");
  const userText = latestUser?.content || "Hello from demo mode.";
  return {
    id: "chatcmpl-demo",
    object: "chat.completion",
    created: 1710000000,
    model: "openai/gpt-oss-120b:free",
    choices: [
      {
        index: 0,
        message: {
          role: "assistant",
          content: `Demo mode reply: ${userText}`,
        },
        finish_reason: "stop",
      },
    ],
    usage: {
      total_tokens: 64,
    },
  };
}
